/* Auto-generated by genmsg_cpp for file /home/xellgadis/attentionwhore/msg/Point.msg */
#ifndef ATTENTIONWHORE_MESSAGE_POINT_H
#define ATTENTIONWHORE_MESSAGE_POINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace attentionwhore
{
template <class ContainerAllocator>
struct Point_ {
  typedef Point_<ContainerAllocator> Type;

  Point_()
  : x(0.0)
  , y(0.0)
  {
  }

  Point_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;


private:
  static const char* __s_getDataType_() { return "attentionwhore/Point"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ff8d7d66dd3e4b731ef14a45d38888b6"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 x\n\
float32 y\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    return size;
  }

  typedef boost::shared_ptr< ::attentionwhore::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::attentionwhore::Point_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Point
typedef  ::attentionwhore::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::attentionwhore::Point> PointPtr;
typedef boost::shared_ptr< ::attentionwhore::Point const> PointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::attentionwhore::Point_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::attentionwhore::Point_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace attentionwhore

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::attentionwhore::Point_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::attentionwhore::Point_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::attentionwhore::Point_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const  ::attentionwhore::Point_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::attentionwhore::Point_<ContainerAllocator> > {
  static const char* value() 
  {
    return "attentionwhore/Point";
  }

  static const char* value(const  ::attentionwhore::Point_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::attentionwhore::Point_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
\n\
";
  }

  static const char* value(const  ::attentionwhore::Point_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::attentionwhore::Point_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::attentionwhore::Point_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Point_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::attentionwhore::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::attentionwhore::Point_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ATTENTIONWHORE_MESSAGE_POINT_H

